name: firestore_service
description: A new Flutter package project.
version: 0.0.1
author: Michael Suleiman
homepage: http://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
